"""add llm conversation id to the user_conversations table and llm message_id to the conversation_messages table

Revision ID: 7d08b2db318b
Revises: afcb96981718
Create Date: 2026-06-11 22:36:04.502787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d08b2db318b'
down_revision: Union[str, Sequence[str], None] = 'afcb96981718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_message', sa.Column('llm_message_id', sa.String(length=255), nullable=True), schema='app')
    op.create_index('ix_conversation_message_llm_message_id', 'conversation_message', ['llm_message_id'], unique=False, schema='app')
    op.add_column('user_conversation', sa.Column('openai_conversation_id', sa.String(length=255), nullable=True), schema='app')
    op.create_index('ix_user_conversation_openai_conversation_id', 'user_conversation', ['openai_conversation_id'], unique=False, schema='app')
    op.create_unique_constraint(None, 'user_conversation', ['openai_conversation_id'], schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_conversation', schema='app', type_='unique')
    op.drop_index('ix_user_conversation_openai_conversation_id', table_name='user_conversation', schema='app')
    op.drop_column('user_conversation', 'openai_conversation_id', schema='app')
    op.drop_index('ix_conversation_message_llm_message_id', table_name='conversation_message', schema='app')
    op.drop_column('conversation_message', 'llm_message_id', schema='app')
    # ### end Alembic commands ###
