"""updated file chunks

Revision ID: ac81b6f702bb
Revises: ad460a388306
Create Date: 2026-05-13 21:14:17.889414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac81b6f702bb'
down_revision: Union[str, Sequence[str], None] = 'ad460a388306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_file_chunk_file_id_chunk_index', 'file_chunk', ['file_id', 'chunk_index'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_file_chunk_file_id_chunk_index', table_name='file_chunk', schema='app')
    # ### end Alembic commands ###
