"""adding sender to messages table

Revision ID: afcb96981718
Revises: dd6df51c5be8
Create Date: 2026-05-26 22:05:02.621006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcb96981718'
down_revision: Union[str, Sequence[str], None] = 'dd6df51c5be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_message', sa.Column('sender_is_agent', sa.Boolean(), nullable=False, default=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_message', 'sender_is_agent', schema='app')
    # ### end Alembic commands ###
