"""Add tables for chunking and embedding for docs

Revision ID: b0c6bec63d5c
Revises: e6a8efbfd118
Create Date: 2026-04-14 20:49:59.332018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0c6bec63d5c'
down_revision: Union[str, Sequence[str], None] = 'e6a8efbfd118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('conversation_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id'),
    schema='app'
    )
    op.create_index('ix_user_conversation_user_id', 'user_conversation', ['user_id'], unique=False, schema='app')
    op.create_table('conversation_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_conversation_id'], ['app.user_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_conversation_message_user_conversation_id', 'conversation_message', ['user_conversation_id'], unique=False, schema='app')
    op.create_table('file_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['app.user_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_file_chunk_file_id', 'file_chunk', ['file_id'], unique=False, schema='app')
    op.create_table('agent_query_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_conversation_id', sa.Integer(), nullable=False),
    sa.Column('conversation_message_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=255), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_message_id'], ['app.conversation_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_conversation_id'], ['app.user_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_agent_query_log_conversation_message_id', 'agent_query_log', ['conversation_message_id'], unique=False, schema='app')
    op.create_index('ix_agent_query_log_user_conversation_id', 'agent_query_log', ['user_conversation_id'], unique=False, schema='app')
    op.create_index('ix_agent_query_log_user_id', 'agent_query_log', ['user_id'], unique=False, schema='app')
    op.create_table('retrieval_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_log_id', sa.Integer(), nullable=False),
    sa.Column('retrieved_file_id', sa.Integer(), nullable=False),
    sa.Column('retrieved_file_chunk_id', sa.Integer(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=False),
    sa.Column('retrieval_rank', sa.Integer(), nullable=False),
    sa.Column('retrieval_name', sa.String(length=255), nullable=True),
    sa.Column('retrieval_strategy', sa.String(length=255), nullable=True),
    sa.Column('filter_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_log_id'], ['app.user_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieved_file_chunk_id'], ['app.file_chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieved_file_id'], ['app.user_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index('ix_retrieval_log_query_log_id', 'retrieval_log', ['query_log_id'], unique=False, schema='app')
    op.create_index('ix_retrieval_log_retrieval_rank', 'retrieval_log', ['retrieval_rank'], unique=False, schema='app')
    op.create_index('ix_retrieval_log_retrieval_score', 'retrieval_log', ['retrieval_score'], unique=False, schema='app')
    op.create_index('ix_retrieval_log_retrieved_file_id', 'retrieval_log', ['retrieved_file_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retrieval_log_retrieved_file_id', table_name='retrieval_log', schema='app')
    op.drop_index('ix_retrieval_log_retrieval_score', table_name='retrieval_log', schema='app')
    op.drop_index('ix_retrieval_log_retrieval_rank', table_name='retrieval_log', schema='app')
    op.drop_index('ix_retrieval_log_query_log_id', table_name='retrieval_log', schema='app')
    op.drop_table('retrieval_log', schema='app')
    op.drop_index('ix_agent_query_log_user_id', table_name='agent_query_log', schema='app')
    op.drop_index('ix_agent_query_log_user_conversation_id', table_name='agent_query_log', schema='app')
    op.drop_index('ix_agent_query_log_conversation_message_id', table_name='agent_query_log', schema='app')
    op.drop_table('agent_query_log', schema='app')
    op.drop_index('ix_file_chunk_file_id', table_name='file_chunk', schema='app')
    op.drop_table('file_chunk', schema='app')
    op.drop_index('ix_conversation_message_user_conversation_id', table_name='conversation_message', schema='app')
    op.drop_table('conversation_message', schema='app')
    op.drop_index('ix_user_conversation_user_id', table_name='user_conversation', schema='app')
    op.drop_table('user_conversation', schema='app')
    # ### end Alembic commands ###
