"""changes to user_conversations

Revision ID: dd6df51c5be8
Revises: ac81b6f702bb
Create Date: 2026-05-18 22:02:41.750680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd6df51c5be8'
down_revision: Union[str, Sequence[str], None] = 'ac81b6f702bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_conversation', sa.Column('relevant_file_ids', postgresql.ARRAY(sa.UUID()), nullable=True), schema='app')
    op.drop_index(op.f('ix_user_conversation_user_id'), table_name='user_conversation', schema='app')
    op.create_unique_constraint('uq_user_file_user_id_conversation_id', 'user_conversation', ['user_id', 'conversation_id'], schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_file_user_id_conversation_id', 'user_conversation', schema='app', type_='unique')
    op.create_index(op.f('ix_user_conversation_user_id'), 'user_conversation', ['user_id'], unique=False, schema='app')
    op.drop_column('user_conversation', 'relevant_file_ids', schema='app')
    # ### end Alembic commands ###
