"""adding user_file and file_job tables

Revision ID: de830552a946
Revises: 7ef8e844decf
Create Date: 2026-04-09 15:45:08.869572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de830552a946'
down_revision: Union[str, Sequence[str], None] = '7ef8e844decf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('storage_key'),
    schema='app'
    )
    op.create_index('ix_user_file_created_at', 'user_file', ['created_at'], unique=False, schema='app')
    op.create_index('ix_user_file_status', 'user_file', ['status'], unique=False, schema='app')
    op.create_index('ix_user_file_user_id', 'user_file', ['user_id'], unique=False, schema='app')
    op.create_table('file_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['app.user_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    schema='app'
    )
    op.create_index('ix_file_job_created_at', 'file_job', ['created_at'], unique=False, schema='app')
    op.create_index('ix_file_job_file_id', 'file_job', ['file_id'], unique=False, schema='app')
    op.create_index('ix_file_job_job_type', 'file_job', ['job_type'], unique=False, schema='app')
    op.create_index('ix_file_job_status', 'file_job', ['status'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_job_status', table_name='file_job', schema='app')
    op.drop_index('ix_file_job_job_type', table_name='file_job', schema='app')
    op.drop_index('ix_file_job_file_id', table_name='file_job', schema='app')
    op.drop_index('ix_file_job_created_at', table_name='file_job', schema='app')
    op.drop_table('file_job', schema='app')
    op.drop_index('ix_user_file_user_id', table_name='user_file', schema='app')
    op.drop_index('ix_user_file_status', table_name='user_file', schema='app')
    op.drop_index('ix_user_file_created_at', table_name='user_file', schema='app')
    op.drop_table('user_file', schema='app')
    # ### end Alembic commands ###
