"""Add unique constraint to user_files

Revision ID: e6a8efbfd118
Revises: de830552a946
Create Date: 2026-04-13 19:22:32.404534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a8efbfd118'
down_revision: Union[str, Sequence[str], None] = 'de830552a946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_file_user_id_storage_key_status', 'user_file', ['user_id', 'storage_key', 'status'], schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_file_user_id_storage_key_status', 'user_file', schema='app', type_='unique')
    # ### end Alembic commands ###
